# Generated by Django 4.0.3 on 2022-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_main_adress', models.CharField(max_length=250)),
                ('bank_phone', models.CharField(max_length=20)),
                ('bank_short_desc', models.CharField(max_length=250)),
                ('bank_site_url', models.URLField()),
                ('bank_logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
