# Generated by Django 4.0.3 on 2022-03-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Банк', 'verbose_name_plural': 'Банки'},
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_fin_assets',
            field=models.IntegerField(default=0, verbose_name='активы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_fin_deposit',
            field=models.IntegerField(default=0, verbose_name='Вклады/депозиты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_fin_fiz_credit',
            field=models.IntegerField(default=0, verbose_name='Кредиты физ лицам'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_fin_profit',
            field=models.IntegerField(default=0, verbose_name='Прибыль банка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_license',
            field=models.IntegerField(default=0, verbose_name='Номер лицензии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_off_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во отделений в России'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_logo',
            field=models.ImageField(upload_to='', verbose_name='Логотип банка'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_main_adress',
            field=models.CharField(max_length=250, verbose_name='Главный офис'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_short_desc',
            field=models.CharField(max_length=250, verbose_name='Описание банка'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_site_url',
            field=models.URLField(verbose_name='адрес сайта'),
        ),
    ]
