# Generated by Django 4.0.3 on 2022-03-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_bank_options_bank_bank_fin_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_adress_index',
            field=models.CharField(max_length=250, null=True, verbose_name='Индекс офиса'),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Полное наименование банка'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_fin_assets',
            field=models.IntegerField(null=True, verbose_name='активы'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_fin_deposit',
            field=models.IntegerField(null=True, verbose_name='Вклады/депозиты'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_fin_fiz_credit',
            field=models.IntegerField(null=True, verbose_name='Кредиты физ лицам'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_fin_profit',
            field=models.IntegerField(null=True, verbose_name='Прибыль банка'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_main_adress',
            field=models.CharField(max_length=250, null=True, verbose_name='Главный офис'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_short_desc',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание банка'),
        ),
    ]
