# Generated by Django 4.0.3 on 2022-03-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_bank_bank_adress_index_bank_bank_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_logo',
            field=models.ImageField(upload_to='bank_logo', verbose_name='Логотип банка'),
        ),
    ]
