# Generated by Django 4.0.3 on 2022-03-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_alter_bank_bank_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_fin_assets',
            field=models.IntegerField(blank=True, null=True, verbose_name='активы'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_fin_deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вклады/депозиты'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_fin_fiz_credit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кредиты физ лицам'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_fin_profit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Прибыль банка'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_off_count',
            field=models.IntegerField(blank=True, verbose_name='Кол-во отделений в России'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_short_desc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание банка'),
        ),
    ]
