# Generated by Django 4.0.3 on 2022-03-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_alter_bank_bank_fin_assets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_logo',
            field=models.ImageField(upload_to="{% static 'bank_logo/' %}", verbose_name='Логотип банка'),
        ),
    ]
