# Generated by Django 4.0.3 on 2022-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_alter_bank_bank_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_logo',
            field=models.ImageField(upload_to='onebank/static/bank_logo/', verbose_name='Логотип банка'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_off_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во отделений в России'),
        ),
    ]
