# Generated by Django 4.0.3 on 2022-03-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_alter_bank_bank_logo_alter_bank_bank_off_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_logo',
            field=models.ImageField(upload_to='bank_logo/', verbose_name='Логотип банка'),
        ),
    ]
