# Generated by Django 4.0.3 on 2022-03-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_alter_bank_bank_fin_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_mainfin_url',
            field=models.URLField(blank=True, null=True, verbose_name='адрес ссылки mainfin'),
        ),
    ]
