# Generated by Django 4.0.3 on 2022-03-24 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0010_bank_bank_mainfin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreditOffer_name', models.CharField(max_length=100, verbose_name='Наименование офера')),
                ('CreditOffer_description', models.CharField(max_length=100, null=True, verbose_name='Описание оффера')),
                ('CreditOffer_active', models.BooleanField(default=False, null=True, verbose_name='Актиный оффер')),
                ('CreditOffer_advert_rate', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Рекламная ставка')),
                ('CreditOffer_sum_min', models.IntegerField(verbose_name='Минимальная сумма кредита')),
                ('CreditOffer_sum_max', models.IntegerField(verbose_name='Максимальная  сумма кредита')),
                ('CreditOffer_loan_term_min', models.IntegerField(verbose_name='Минимальная период кредита')),
                ('CreditOffer_loan_term_max', models.IntegerField(verbose_name='Максимальный период кредита')),
                ('CreditOffer_review_period', models.CharField(max_length=255, null=True, verbose_name='Период рассмотрения')),
                ('CreditOffer_offer_link_mainfin', models.URLField(verbose_name='адрес ссылки на оффер mainfin')),
                ('CreditOffer_offer_link', models.URLField(verbose_name='адрес ссылки на оффер')),
                ('CreditOffer_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
            },
        ),
    ]
